### ISSUE TITLE
Applications Icons are displayed in Workspaces View

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gnome-shell#71] opened 2021-06-25 15:53 UTC
To reproduce: Use `Super + A` to open Applications. Close Applications. Use `Super + D` to open Workspaces. 

This may occur using buttons/icons as well but I haven't tested that.

**Comment by jacobgkau** [comment] 2021-06-25 15:56
Duplicate of https://github.com/pop-os/cosmic/issues/92.

**Closed as completed** 2021-06-25 15:57 UTC
