### ISSUE TITLE
Popos application launcher is very slow

### ISSUE THREAD

**Issue by talhajunaidd** [pop-os/gnome-shell#72] opened 2021-07-01 19:13 UTC
The new PopOS application launcher is very slow

Following are the system details

```
OS: Pop!_OS 21.04 x86_64 
Host: Inspiron 3580 
Kernel: 5.11.0-7620-generic 
Uptime: 6 hours, 59 mins 
Packages: 3689 (dpkg), 52 (flatpak), 13 (snap) 
Shell: bash 5.1.4 
Resolution: 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: korla [GTK2/3] 
Terminal: tilix 
CPU: Intel i7-8565U (8) @ 4.600GHz 
GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
GPU: AMD ATI Radeon R5 M230 / R7 M260DX / Radeon 520 Mobile 
Memory: 6311MiB / 15737MiB 
```

Following is the graph I generated using `psrecord` it when I search using the launcher it uses too much CPU which render is unusable.  If I search it using application menu it's fast.
```
psrecord gnome-shell-pid --interval 1 --duration 30 --plot plot1.png
```

![plot1](https://user-images.githubusercontent.com/6547611/124177704-0362fd00-daca-11eb-87c7-68fce0c668cf.png)

Happy to provide more details and dig deep.

**Comment by mmstick** [comment] 2021-07-02 01:44
Duplicate of https://github.com/pop-os/shell/issues/1040

**Closed as completed by mmstick** 2021-07-02 01:44 UTC
